# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-22.04"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
  #config.vm.network "private_network", type: "dhcp"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  #Local host port 8080 to guest port 80
  #config.vm.network "forwarded_port", guest: 80, host: 1234


  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #

  config.vm.network "public_network"  # or default NAT

  # Explicit definition for the web VM
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.250.10"
    web.vm.network "forwarded_port", guest: 22, host: 2002, id: "ssh"
    web.vm.network "forwarded_port", guest: 8080, host: 8088
    web.vm.synced_folder "../../../../../cogsi2526-1221322-1201623-1151352", "/home/vagrant/vagrant_CogsiRepository"
    web.vm.provision "shell", path: "script.sh"
    web.vm.box = "bento/ubuntu-22.04"

    web.vm.provider :virtualbox do |vb|
      vb.name = "web"
      vb.memory = "6000"
      vb.cpus = 8
    end
  end

  # Explicit definition for the db VM
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.250.11"
    db.vm.network "forwarded_port", guest: 22, host: 2001, id: "ssh"
    db.vm.network "forwarded_port", guest: 8082, host: 8082
    db.vm.synced_folder "../../../../../cogsi2526-1221322-1201623-1151352", "/home/vagrant/vagrant_CogsiRepository"
    db.vm.provision "shell", path: "script.sh"
    db.vm.box = "bento/ubuntu-22.04"

    db.vm.provider :virtualbox do |vb|
      vb.name = "db"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # nable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end
