FROM gradle:8.5-jdk17 AS builder

WORKDIR /app

COPY --chown=gradle:gradle gradlew gradlew
COPY --chown=gradle:gradle gradle gradle
COPY --chown=gradle:gradle build.gradle settings.gradle gradle.properties ./
RUN chmod +x ./gradlew

COPY --chown=gradle:gradle . /app
RUN ./gradlew clean build -x test --no-daemon

FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update && apt-get install -y openjdk-17-jre-headless netcat iputils-ping bash && apt-get clean
COPY --from=builder /app/build/libs/*.jar app.jar

ENV SPRING_DATASOURCE_URL=jdbc:h2:tcp://db:9092/./jpadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
ENV SPRING_DATASOURCE_USERNAME=sa
ENV SPRING_DATASOURCE_PASSWORD=
ENV SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
ENV SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
