Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "blue" do |blue|
    blue.vm.hostname = "ca6-blue"
    blue.vm.network "private_network", ip: "192.168.56.10"
    blue.vm.network "forwarded_port", guest: 8080, host: 8085
    blue.vm.network "forwarded_port", guest: 8082, host: 8086
    
    blue.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "ca6-blue-vm"
    end

    blue.vm.provision "shell", inline: <<-SHELL
      sleep 20
    SHELL

    blue.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook-blue.yml"
      ansible.verbose = true
      ansible.install = true
      ansible.limit = "all"
      ansible.raw_arguments = ["-f", "1"]
      ansible.inventory_path = "inventory.ini"
      ansible.extra_vars = {
        git_token: ENV['GIT_TOKEN'] || ""
      }
    end
  end

  config.vm.define "green" do |green|
    green.vm.hostname = "ca6-green"
    green.vm.network "private_network", ip: "192.168.56.11"
    green.vm.network "forwarded_port", guest: 8080, host: 8087
    green.vm.network "forwarded_port", guest: 8082, host: 8088
    
    green.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "ca6-green-vm"
    end

    green.vm.provision "shell", inline: <<-SHELL
      sleep 20
    SHELL

    green.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook-green.yml"
      ansible.verbose = true
      ansible.install = true
      ansible.limit = "green"
      ansible.raw_arguments = ["-f", "1"]
      ansible.inventory_path = "inventory.ini"
      ansible.extra_vars = {
        git_token: ENV['GIT_TOKEN'] || ""
      }
    end
  end
end
