# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.ssh.insert_key = false

  config.vm.provision "file", source: File.expand_path("~/.ssh/my_vagrant_key.pub"), destination: "/tmp/my_vagrant_key.pub"

  config.vm.provision "shell", inline: <<-SHELL
  PUB=$(cat /tmp/my_vagrant_key.pub || true)
    if [ -n "$PUB" ]; then
      grep -qxF "$PUB" /home/vagrant/.ssh/authorized_keys || echo "$PUB" >> /home/vagrant/.ssh/authorized_keys
    fi

    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    rm -f /tmp/my_vagrant_key.pub
  SHELL

  config.vm.network "public_network" 

  config.vm.define "host1" do |host1|
    host1.vm.hostname = "host1"  
    host1.vm.network "private_network", ip: "192.168.250.10"
    host1.vm.network "forwarded_port", guest: 8080, host: 8088
    host1.vm.network "forwarded_port", guest: 22, host: 2002, id: "ssh"
    
    host1.vm.synced_folder "salt/", "/srv/salt/"
    host1.vm.synced_folder "../../../../../cogsi2526-1221322-1201623-1151352", "/home/vagrant/vagrant_CogsiRepository"

    host1.vm.provider :virtualbox do |vb|
      vb.name = "host1"
      vb.memory = "6000"
      vb.cpus = 8
    end

    host1.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "salt/minion"
      salt.minion_id = "host1"
      salt.run_highstate = true
      salt.colorize = true
      salt.verbose = true
      salt.bootstrap_options = "-P" 
    end
  end

  config.vm.define "host2" do |host2|
    host2.vm.hostname = "host2"  
    host2.vm.network "private_network", ip: "192.168.250.11"
    host2.vm.network "forwarded_port", guest: 9092, host: 8082
    host2.vm.network "forwarded_port", guest: 22, host: 2001, id: "ssh"
    
    host2.vm.synced_folder "salt/", "/srv/salt/"
    host2.vm.synced_folder "../../../../../cogsi2526-1221322-1201623-1151352", "/home/vagrant/vagrant_CogsiRepository"

    host2.vm.provider :virtualbox do |vb|
      vb.name = "host2"
      vb.memory = "2048"
      vb.cpus = 2
    end

    host2.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "salt/minion"
      salt.minion_id = "host2"
      salt.run_highstate = true
      salt.colorize = true
      salt.verbose = true
      salt.bootstrap_options = "-P" 
    end
  end
end
