-- 1. DROP objects 
DROP SEQUENCE IF EXISTS EMPLOYEE_SEQ;
DROP SEQUENCE IF EXISTS CUSTOMER_ORDER_SEQ;
DROP TABLE IF EXISTS EMPLOYEE;
-- Change this table name:
DROP TABLE IF EXISTS ORDERS; 

-- 2. CREATE SEQUENCES (You already did this correctly)
CREATE SEQUENCE EMPLOYEE_SEQ START WITH 1 INCREMENT BY 50; 
CREATE SEQUENCE CUSTOMER_ORDER_SEQ START WITH 1 INCREMENT BY 50; 


-- 3. CREATE TABLES matching Hibernate's expected name
-- Change ORDERS to CUSTOMER_ORDER
CREATE TABLE EMPLOYEE (
    ID BIGINT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    ROLE VARCHAR(255)
);

CREATE TABLE CUSTOMER_ORDER (  -- <--- NAME CHANGED HERE
    ID BIGINT NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    STATUS VARCHAR(255)
);