Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.ssh.insert_key = false

  # Copy custom public SSH key to VM (temporary location) and append it safely
  config.vm.provision "file", source: File.expand_path("~/.ssh/my_vagrant_key.pub"), destination: "/tmp/my_vagrant_key.pub"

  # Create .ssh if needed, append pubkey idempotently, set secure perms and cleanup
  config.vm.provision "shell", inline: <<-SHELL

  PUB=$(cat /tmp/my_vagrant_key.pub || true)
    if [ -n "$PUB" ]; then
      grep -qxF "$PUB" /home/vagrant/.ssh/authorized_keys || echo "$PUB" >> /home/vagrant/.ssh/authorized_keys
    fi

    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    rm -f /tmp/my_vagrant_key.pub
  SHELL

  config.vm.network "public_network"  # or default NAT

  # Explicit definition for the web VM
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.250.10"
    web.vm.network "forwarded_port", guest: 22, host: 2002, id: "ssh"
    web.vm.network "forwarded_port", guest: 8080, host: 8088
    web.vm.synced_folder "../../../../../cogsi2526-1221322-1201623-1151352", "/home/vagrant/vagrant_CogsiRepository"
    web.vm.synced_folder "./ansible", "/home/vagrant/ansible"
    web.vm.box = "bento/ubuntu-22.04"

    web.vm.provider :virtualbox do |vb|
      vb.name = "web"
      vb.memory = "6000"
      vb.cpus = 8
    end
  end

  # Explicit definition for the db VM
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.250.11"
    db.vm.network "forwarded_port", guest: 22, host: 2001, id: "ssh"
    db.vm.network "forwarded_port", guest: 8082, host: 8082
    db.vm.synced_folder "../../../../../cogsi2526-1221322-1201623-1151352", "/home/vagrant/vagrant_CogsiRepository"
    db.vm.synced_folder "./ansible", "/home/vagrant/ansible"
    db.vm.box = "bento/ubuntu-22.04"

    db.vm.provider :virtualbox do |vb|
      vb.name = "db"
      vb.memory = "2048"
      vb.cpus = 8
    end
  end


  #Use the Ansible Local provisioner
  config.vm.provision "ansible_local" do |ansible|
    # ensure Ansible is installed in the guest
    ansible.install  = true
    # file in your project root on Windows
    ansible.playbook = "/home/vagrant/ansible/playbook.yml"
  end

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # nable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end
