Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "public_network"  # or default NAT

  # Explicit definition for the web VM
  config.vm.define "ProductionVm" do |pd|
    pd.vm.hostname = "ProductionVm"
    pd.vm.network "private_network", ip: "192.168.250.10"
    pd.vm.network "forwarded_port", guest: 8080, host: 8088
    pd.vm.synced_folder "./ansible", "/home/vagrant/ansible"

    pd.vm.provision "ansible_local" do |ansible|
      ansible.install  = true
      ansible.playbook = "/home/vagrant/ansible/playbook.yml"
    end


    pd.vm.provider :virtualbox do |vb|
      vb.name = "ProductionVm"
      vb.memory = "6000"
      vb.cpus = 8
    end
  end

end
