pipeline {
    agent any

    options{
        skipDefaultCheckout()
    }

    environment {
        DOCKER_IMAGE_TAG = 'rafalu2225/cogsi_ca6:latest'
    }

    stages {
        // 1. Checkout – Pull the latest source code from your repository
        stage('Checkout') {
            steps {
              echo 'Source code from repository successfully checked out...'
            }
        }

        // 2. Assemble – Compile the code and produce the artifact files
        stage('Assemble') {
            steps {
                echo 'Compiling code and producing artifacts...'
                dir('PLS/CA6/Part2/Web')  {
                  sh 'chmod +x ./gradlew'
                  sh './gradlew clean build'
                }
            }
        }

        // 3. Test – Run unit and integration tests to verify the application’s correctness. Publish the test results in Jenkins
        stage('Test') {
          steps {
            echo "Running tests on Linux..."
            dir('PLS/CA6/Part2/Web')  {
                sh './gradlew test'
            }
            echo 'Publishing aggregated test results...'
            junit '**/*/test-results/test/*.xml'
        }
        }

        stage('Tag Docker Image') {
            steps {
                script {
                    def appDir = 'PLS/CA6/Part2/'
                    
                    sh "docker build -t ${env.DOCKER_IMAGE_TAG} ${appDir}"
                    echo "Successfully built and tagged image: ${env.DOCKER_IMAGE_TAG}"
                }
            }
        }

        // 5. Archive – Archive the Dockerfile and related metadata in Jenkins for traceability and future reference
        stage('Archive') {
            steps {
                echo "Archiving Dockerfile and build metadata..."
                archiveArtifacts artifacts: 'Dockerfile', fingerprint: true
            }
        }

        // 6. Push Docker Image – Push the tagged Docker image to Docker Hub
        stage('Push Docker Image') {
            steps {
                echo "Pushing Docker image ${env.DOCKER_IMAGE_TAG} to Docker Hub..."

                withCredentials(
                    [usernamePassword
                    (credentialsId: 'dockerhub-info',
                     passwordVariable: 'DOCKER_PASSWORD',
                      usernameVariable: 'DOCKER_USERNAME'
                      )
                    ]) 
                {
                    sh "echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin"
                    sh "docker push ${env.DOCKER_IMAGE_TAG}"
                }
            }
        }

        // 7. Deploy – Use an Ansible playbook for the deployment of the latest Docker image (to Production)
        stage('Deploy to Production') {
            steps {
                echo "Deploying ${env.DOCKER_IMAGE_TAG} to production using Ansible..."
                dir('PLS/CA6/Part2/VagrantFile/') { 
                    sh 'chmod -x ./ansible/ansiblePass.txt'
                    sh "vagrant up ProductionVm"
                }
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully!"
        }
        failure {
            echo "❌ Pipeline failed at one or more stages!"
        }
    }
}
