---
- name: Provision VM
  hosts: all
  become: true
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install PAM packages for password policies
      apt:
        name:
          - libpam-pwquality
          - libpam-modules
        state: present

    #- name: Docker Installation
    # apt:
    #   name:
    #      - docker-ce
    ##     - docker-ce-cli
    #     - containerd.io
    #     - docker-buildx-plugin
    #     - docker-compose-plugin
    #   state: present

    - name: Clone the repository
      git:
        repo: https://github.com/RafaeLuisPrf/cogsi2526-1221322-1201623-1151352.git
        dest: /home/vagrant/masters/cogsi_CA4_P1
        version: main # Adjust branch if needed
      become_user: vagrant # Run as vagrant user

    - name: Install Docker using official convenience script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

- name: Setup Docker Access
  hosts: all
  become: true # Need root permissions to modify users and groups

  tasks:
    - name: Ensure the remote user is in the 'docker' group
      ansible.builtin.user:
        name: '{{ ansible_user_id }}' # This variable holds the current remote connection user (e.g., 'vagrant')
        groups: docker
        append: true

- name: Docker Registry Login
  hosts: all
  become: true

  tasks:
    - name: Log into Docker Hub
      community.docker.docker_login:
        username: 'rafalu2225' #"{{ docker_registry_username }}"
        password: 'dckr_pat_FYswjpK31VabEG7dYPMHLzkGbxQ'
        state: present

    - name: Pull the docker image from Docker Hub
      community.docker.docker_image:
        name: rafalu2225/cogsi_ca6
        tag: latest
        state: present
        source: pull

    - name: Run the Application Container
      community.docker.docker_container:
        name: ca6-web-app # Defina um nome para o container
        image: rafalu2225/cogsi_ca6:latest-1
        state: started
        restart_policy: always # Garante que o container reinicie automaticamente
        ports:
          - '8080:8081' # Mapeia a porta 8080 do host para a porta 8080 do container
